(()=>{"use strict";
const $=id=>document.getElementById(id), KEY={notes:"alduin_notes_v2",profile:"alduin_profile_v2",avatar:"alduin_avatar_v2",settings:"alduin_settings_v2"}, CREATED=Date.parse("2026-08-02T00:00:00Z");let db,notes=[],photos=[],viewerIndex=0;
const toast=t=>{let e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
function dbOpen(){return new Promise((ok,no)=>{let r=indexedDB.open("alduin_ultimate_v2",1);r.onupgradeneeded=()=>r.result.createObjectStore("photos",{keyPath:"id",autoIncrement:true});r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
function tx(mode){return db.transaction("photos",mode).objectStore("photos")}
const getPhotos=()=>new Promise((ok,no)=>{let r=tx("readonly").getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const putPhoto=x=>new Promise((ok,no)=>{let r=tx("readwrite").add(x);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});
const removePhoto=id=>new Promise((ok,no)=>{let r=tx("readwrite").delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});
function nav(){document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(page){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(page).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));scrollTo({top:0,behavior:"smooth"})}
function renderNotes(){let q=$("noteSearch").value.toLowerCase();let list=notes.filter(n=>(n.title+" "+n.text+" "+n.tags).toLowerCase().includes(q)).sort((a,b)=>b.date-a.date);$("notesList").innerHTML=list.length?list.map(n=>`<article class="note card"><div class="card-head"><div><h3>${esc(n.title||"Без названия")}</h3><small>${new Date(n.date).toLocaleString("ru-RU")} · ${esc(n.mood)}</small></div><button data-del-note="${n.id}">×</button></div><p>${esc(n.text).replace(/\n/g,"<br>")}</p><small class="muted">${esc(n.tags)}</small></article>`).join(""):`<div class="empty">Ничего не найдено.</div>`;document.querySelectorAll("[data-del-note]").forEach(b=>b.onclick=()=>{notes=notes.filter(n=>n.id!==b.dataset.delNote);save(KEY.notes,notes);renderNotes();renderAll();toast("Запись удалена")})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function clearEditor(){$("noteTitle").value="";$("noteText").value="";$("noteTags").value=""}
function saveNote(){let text=$("noteText").value.trim();if(!text){toast("Напиши текст записи");return}notes.push({id:crypto.randomUUID(),date:Date.now(),title:$("noteTitle").value.trim(),text,mood:$("noteMood").value,tags:$("noteTags").value.trim()});save(KEY.notes,notes);clearEditor();renderNotes();renderAll();toast("Запись сохранена")}
function renderTimeline(){let a=[...notes].sort((x,y)=>y.date-x.date);$("timelineList").innerHTML=a.length?a.map(n=>`<div class="timeline-item"><small>${new Date(n.date).toLocaleString("ru-RU")}</small><h3>${esc(n.mood)} ${esc(n.title||"Без названия")}</h3><p>${esc(n.text).slice(0,400)}</p></div>`).join(""):`<div class="empty card">Хронология пока пуста.</div>`}
async function renderGallery(){let q=$("gallerySearch").value.toLowerCase(),sort=$("gallerySort").value;let a=photos.filter(p=>p.name.toLowerCase().includes(q));a.sort((x,y)=>sort==="old"?x.date-y.date:sort==="name"?x.name.localeCompare(y.name):y.date-x.date);$("galleryGrid").innerHTML=a.map(p=>`<div class="gallery-item"><img loading="lazy" decoding="async" src="${p.data}" data-view="${p.id}"><button class="g-delete" data-del="${p.id}">×</button></div>`).join("");$("galleryEmpty").hidden=photos.length>0;document.querySelectorAll("[data-view]").forEach(i=>i.onclick=()=>openViewer(i.dataset.view));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("Удалить изображение?")){await removePhoto(Number(b.dataset.del));photos=await getPhotos();renderAll();renderGallery();toast("Изображение удалено")}})}
function openViewer(id){viewerIndex=photos.findIndex(x=>String(x.id)===String(id));if(viewerIndex<0)return;$("viewerImg").src=photos[viewerIndex].data;$("viewer").hidden=false}
function moveViewer(d){if(!photos.length)return;viewerIndex=(viewerIndex+d+photos.length)%photos.length;$("viewerImg").src=photos[viewerIndex].data}
function renderDashboard(){$("days").textContent=Math.max(0,Math.floor((Date.now()-CREATED)/86400000));$("noteCount").textContent=notes.length;$("photoCount").textContent=photos.length;let n=[...notes].sort((a,b)=>b.date-a.date)[0];$("dashLast").innerHTML=n?`<h3>${esc(n.title||"Без названия")}</h3><p>${esc(n.text).slice(0,280)}</p>`:"Записей пока нет.";$("dashPhotos").innerHTML=photos.slice().sort((a,b)=>b.date-a.date).slice(0,4).map(p=>`<img src="${p.data}" data-view="${p.id}">`).join("");$("dashPhotos").querySelectorAll("[data-view]").forEach(i=>i.onclick=()=>openViewer(i.dataset.view))}
function renderProfile(){let p=load(KEY.profile,{});$("pName").value=p.name||"Alduin";$("pType").value=p.type||"Тульпа";$("pOrigin").value=p.origin||"Original Character";$("pTags").value=p.tags||"";$("pDescription").value=p.description||"";let av=localStorage.getItem(KEY.avatar);if(av)$("avatar").src=av}
function saveProfile(){save(KEY.profile,{name:$("pName").value,type:$("pType").value,origin:$("pOrigin").value,tags:$("pTags").value,description:$("pDescription").value});toast("Профиль сохранён")}
function renderAll(){renderDashboard();renderTimeline();renderNotes()}
function particles(){let box=$("particles"),c=document.createElement("canvas");box.append(c);let x=c.getContext("2d"),a=[],dpr=Math.min(devicePixelRatio||1,2);function resize(){c.width=innerWidth*dpr;c.height=innerHeight*dpr;c.style.width=innerWidth+"px";c.style.height=innerHeight+"px";x.setTransform(dpr,0,0,dpr,0,0);a=Array.from({length:Math.min(70,Math.floor(innerWidth/15))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.6+.3,v:Math.random()*.18+.04,o:Math.random()*.6+.15}))}resize();addEventListener("resize",resize,{passive:true});let last=performance.now();function frame(t){let dt=Math.min(32,t-last);last=t;x.clearRect(0,0,innerWidth,innerHeight);for(let p of a){p.y-=p.v*dt;if(p.y<0)p.y=innerHeight;x.globalAlpha=p.o;x.fillStyle="#c18aff";x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill()}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function settings(){let s=load(KEY.settings,{fx:true,glow:true,motion:true});$("fxToggle").checked=s.fx;$("glowToggle").checked=s.glow;$("motionToggle").checked=s.motion;function apply(){document.body.classList.toggle("no-particles",!$("fxToggle").checked);document.body.classList.toggle("no-glow",!$("glowToggle").checked);document.body.classList.toggle("no-motion",!$("motionToggle").checked);save(KEY.settings,{fx:$("fxToggle").checked,glow:$("glowToggle").checked,motion:$("motionToggle").checked})}["fxToggle","glowToggle","motionToggle"].forEach(id=>$(id).onchange=apply);apply()}
async function exportData(){let d={version:2,date:new Date().toISOString(),notes,profile:load(KEY.profile,{}),avatar:localStorage.getItem(KEY.avatar)||"",photos};let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(d)],{type:"application/json"}));a.download="ALDUIN_ULTIMATE_BACKUP.json";a.click();toast("Резервная копия готова")}
function importData(){let i=document.createElement("input");i.type="file";i.accept=".json";i.onchange=async()=>{try{let d=JSON.parse(await i.files[0].text());if(Array.isArray(d.notes)){notes=d.notes;save(KEY.notes,notes)}if(d.profile)save(KEY.profile,d.profile);if(d.avatar)localStorage.setItem(KEY.avatar,d.avatar);for(let p of d.photos||[])await putPhoto(p);photos=await getPhotos();renderAll();renderGallery();renderProfile();toast("Данные восстановлены")}catch{toast("Не удалось импортировать файл")}};i.click()}
async function boot(){try{await dbOpen()}catch(e){toast("IndexedDB недоступен — галерея отключена")}notes=load(KEY.notes,[]);photos=await getPhotos();renderProfile();renderAll();renderGallery();nav();settings();$("saveNote").onclick=saveNote;$("clearEditor").onclick=clearEditor;$("noteSearch").oninput=renderNotes;$("gallerySearch").oninput=renderGallery;$("gallerySort").onchange=renderGallery;$("imageInput").onchange=async e=>{for(let f of e.target.files){if(!f.type.startsWith("image/"))continue;let r=await new Promise(ok=>{let fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(f)});await putPhoto({name:f.name,data:r,date:Date.now()})}photos=await getPhotos();e.target.value="";renderAll();renderGallery();toast("Изображения добавлены")};$("avatarInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let fr=new FileReader();fr.onload=()=>{localStorage.setItem(KEY.avatar,fr.result);$("avatar").src=fr.result};fr.readAsDataURL(f)};$("saveProfile").onclick=saveProfile;$("viewerClose").onclick=()=>$("viewer").hidden=true;$("viewerPrev").onclick=()=>moveViewer(-1);$("viewerNext").onclick=()=>moveViewer(1);$("viewer").onclick=e=>{if(e.target.id==="viewer")$("viewer").hidden=true};document.onkeydown=e=>{if($("viewer").hidden)return;if(e.key==="Escape")$("viewer").hidden=true;if(e.key==="ArrowLeft")moveViewer(-1);if(e.key==="ArrowRight")moveViewer(1)};$("exportBtn").onclick=exportData;$("importBtn").onclick=importData;$("clearBtn").onclick=async()=>{if(confirm("Удалить ВСЕ локальные данные?")){localStorage.clear();try{let r=tx("readwrite").clear();r.onsuccess=()=>location.reload()}catch{location.reload()}}};particles();setInterval(()=>{$("clock").textContent=new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})},1000);$("clock").textContent=new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});requestAnimationFrame(()=>setTimeout(()=>$("loader").classList.add("hide"),450))}
if(document.readyState==="loading")addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();